### ISSUE TITLE
Does not load the plugin

### ISSUE THREAD

**Issue by Norrox** [TheRensei/godot_spicyparticlesystem#1]
I do not know if i'm doing it wrong, but it does not seem to load the plugin.
![image](https://github.com/TheRensei/godot_spicyparticlesystem/assets/13393087/773a058b-261d-46da-a844-61e462c1014e)

using kde neon, godot 4.3 dev 1

**Comment by TheRensei** [comment]
Hi! Unless you get any errors after importing it should have been loaded already. It will not show up in the project plugin list ^^

**Comment by Norrox** [comment]
Thanks, yea it works :)
